const cities = [
  { name: "Yerevan", timezone: "Asia/Yerevan" },
  { name: "Auckland", timezone: "Pacific/Auckland" },
  { name: "Sydney", timezone: "Australia/Sydney" },
  { name: "Tokyo", timezone: "Asia/Tokyo" },
  { name: "Seoul", timezone: "Asia/Seoul" },
  { name: "Papua New Guinea", timezone: "Pacific/Port_Moresby" },
  { name: "Beijing", timezone: "Asia/Shanghai" },
  { name: "Bangkok", timezone: "Asia/Bangkok" },
  { name: "Thailand", timezone: "Asia/Bangkok" },
  { name: "Delhi", timezone: "Asia/Kolkata" },
  { name: "Dubai", timezone: "Asia/Dubai" },
  { name: "Moscow", timezone: "Europe/Moscow" },
  { name: "Saint-Petersburg", timezone: "Europe/Moscow" },
  { name: "Amsterdam", timezone: "Europe/Amsterdam" },
  { name: "Kiev", timezone: "Europe/Kiev" },
  { name: "Minsk", timezone: "Europe/Minsk" },
  { name: "Kishinev", timezone: "Europe/Chisinau" },
  { name: "Athens", timezone: "Europe/Athens" },
  { name: "Paris", timezone: "Europe/Paris" },
  { name: "London", timezone: "Europe/London" },
  { name: "Reykjavik", timezone: "Atlantic/Reykjavik" },
  { name: "Rio de Janeiro", timezone: "America/Sao_Paulo" },
  { name: "Trinidad and Tobago", timezone: "America/Port_of_Spain" },
  { name: "Paraguay", timezone: "America/Asuncion" },
  { name: "Lima", timezone: "America/Lima" },
  { name: "New York", timezone: "America/New_York" },
  { name: "Mexico City", timezone: "America/Mexico_City" },
  { name: "Denver", timezone: "America/Denver" },
  { name: "Los Angeles", timezone: "America/Los_Angeles" },
  { name: "Anchorage", timezone: "America/Anchorage" },
  { name: "Honolulu", timezone: "Pacific/Honolulu" },
  { name: "Marshal Islands", timezone: "Pacific/Majuro" },
  { name: "Cape Town", timezone: "Africa/Johannesburg" },
  { name: "Cairo", timezone: "Africa/Cairo" },
  { name: "Jerusalem", timezone: "Asia/Jerusalem" },
  { name: "New Delhi", timezone: "Asia/Kolkata" },
  { name: "Lisbon", timezone: "Europe/Lisbon" },
  { name: "Montevideo", timezone: "America/Montevideo" },
  { name: "Tbilisi", timezone: "Asia/Tbilisi" },
  { name: "Madrid", timezone: "Europe/Madrid" },
  { name: "Malta", timezone: "Europe/Malta" },
  { name: "Belgrade", timezone: "Europe/Belgrade" },
  { name: "Yekaterinburg", timezone: "Asia/Yekaterinburg" },
  { name: "Ufa", timezone: "Asia/Yekaterinburg" },
  { name: "Oakland", timezone: "America/Los_Angeles" },
  { name: "Toronto", timezone: "America/Toronto" },
  { name: "Ottawa", timezone: "America/Toronto" },
  { name: "Buenos Aires", timezone: "America/Argentina/Buenos_Aires" },
  { name: "Addis Ababa", timezone: "Africa/Addis_Ababa" },
  { name: "Podgorica", timezone: "Europe/Podgorica" },
  { name: "Berlin", timezone: "Europe/Berlin" },
  { name: "Novosibirsk", timezone: "Asia/Novosibirsk" },
  { name: "Nicosia", timezone: "Asia/Nicosia" },
];

export default cities;
